### ISSUE TITLE
Why are there 4096 secret g2 points in the trusted setup?

### ISSUE THREAD

**Issue by jtraglia** [protolambda/go-kzg#38]
Is there a reason there are so many secret g2 points in the [embedded trusted setup](https://github.com/ethereum/c-kzg-4844/blob/13f2a79345cb8739c899253c6b0771f7e875f061/src/trusted_setup.txt#L4099-L4163)? There are 4096 (which matches the number of secret g1 points) but I believe only 65 are required. This is what [C-KZG-4844 uses in their trusted setup](https://github.com/ethereum/c-kzg-4844/blob/main/src/trusted_setup.txt). The secret g1 points & the first 65 secret g2 points do match C-KZG-4844. The number of points seems intentional, as there's this check:

https://github.com/protolambda/go-kzg/blob/c91cee5e954e1506cc940d404a7918e17b258749/kzg.go#L22-L24

**Comment by protolambda** [comment]
The `KZGSettings` code is about a year older than the first shared testing-only KZG trusted setup, and there was no reason to reduce it to less G2 points at the time.

**Comment by jtraglia** [comment]
Ah okay, pretty much what I expected. Would you like for me to make a PR to remove the excess ones?

**Comment by protolambda** [comment]
I think reducing it affects `CheckProofMulti`; multi-proofs must then be smaller. @asn-d6 where can I find the reasoning for the smaller KZG G2? Doesn't this affect data-availability sampling?

**Comment by asn-d6** [comment]
Hey proto. Check out https://github.com/ethereum/consensus-specs/pull/3156 .
